### ISSUE TITLE
Bug Report: Mutations -> user_id

### ISSUE THREAD

**Issue by ghost** [chingu-voyages/v8-chimeras-team-02#40]
Whenever I try to query user, I get a ```"Cannot return null for non-nullable field Question.user." ```error. I am querying the user as such (inside the query or mutation): ```user { _id }``` - ed

![image](https://user-images.githubusercontent.com/2034190/55877183-b0739700-5b99-11e9-8411-51641f20886f.png)

**Comment by hanenWahabi** [comment]
Check out my last pull request this bug is fixed
