### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by joanaammoura** [chingu-voyages/v8-chimeras-team-02#63]
Search is not returning results.

- Should we create a screen SearchResults.js? Because Home.js returns "Top Questions".

**Comment by hanenWahabi** [comment]
I added the possibility to search while pressing the enter key to the search bar if u could test it after merging.
For the Top Questions, it's a static title we can write a general one

**Comment by cMikolai** [comment]
Sorry, I have to re-open the issue. Not sure if this happened after solving merge conflicts, but search only works on Home. Can you have a look? @hanenWahabi 

It should work on Ask & GiveAnswer screens as well.

**Comment by etorres07** [comment]
I'm checking this one out.

I will self-assign the issue and update before I clock out today in case anyone wants to pick it up where I left.

**Comment by etorres07** [comment]
**Update:**
I pushed a separate branch called `search-bug`. Anyone can pull it, work on it locally and then push any changes to that same branch.

In this branch I experimented with several ideas, however, the only changes I implemented so far were:
- redirect users to `Home.js` whenever they searched on a page that was not `Home.js`
- add `searchText: ''` to `state` in `GiveAnswer.js` (this doesn't do anything; it's just part of the experimentation so feel free to ignore this)

**Some comments/ideas on the issue:**
I don't think redirection is an issue.

In my opinion, the biggest challenge is passing the `searchText`, or the data the user searched for, from `GiveAnswer.js` and `NewQuestion.js` to `Home.js`. In other words, finding a way to keep that data the user searched for while redirecting at the same time.

**Suggested approaches:**
1. Creating an additional route to `Home.js` that contains the keyword (e.g. `<url>/search=:keyword`). The redirection executes when `onSearch` on the other screens that are not `Home.js`. The question here would be: how do we tell the app on `Home.js` when to search with `:keyword` and when to search with `this.state.searchText`?
2. Hide the search bar whenever the user is **not** on `Home.js` (this is not a fix but more like a temporary solution given the time constraints).

What do you think?

**Comment by ghost** [comment]
I like your first approach. If we create a route  for `/search/:searchString` we could render Home.js and trigger the search on the render hook. The onSearch() is declared by the screen, but in the SearchBar.js we can declare a fallback function, that links to `/search/:string`
