### ISSUE TITLE
Questions ListItem.js

### ISSUE THREAD

**Issue by joanaammoura** [chingu-voyages/v8-chimeras-team-02#67]
- Date has a strange string on the end.

- The Heart, when clicked, isn't returning a fullfiled Heart and 1 more Like. Instead, it opens the GiveAnswer.js and it shouldn't.

**Comment by etorres07** [comment]
`ListItem` components on `Home.js` now display a formatted date (a bit of a hack but it does the job for now; maybe in the future, if possible, the date can be formatted as soon as it is received from the back-end before passing it to the front-end).

In `Home.js`, now only the title of the question redirects to `GiveAnswer.js`. That was an easy fix.

Thank you, @joanaammoura! 😀
