### ISSUE TITLE
Questions and answers are from previous user

### ISSUE THREAD

**Issue by etorres07** [chingu-voyages/v8-chimeras-team-02#79]
**Issue:** if I log in as "edd", then log out, and then I sign up as a different user, the questions I ask are still displayed as edd's and not as the last user I signed up as.

**Steps to recreate:**
1. Log in or sign up
2. Log out
3. Sign up as a different user
4. Create a question or submit an answer

**Expected functionality:** the user displayed in the questions and answers should be the one that is currently logged in and not any of the previous ones.

**Comment by hanenWahabi** [comment]
I tested this scenario but there is no bug because in the last version we are using a static username for both creating and answering a question.
With PR #4238d0d fixes it

**Comment by etorres07** [comment]
Fixed!

Thank you @hanenWahabi :)
