### ISSUE TITLE
Styling inconsistency between 'ListItem', 'CompleteItem' and 'Answer'

### ISSUE THREAD

**Issue by etorres07** [chingu-voyages/v8-chimeras-team-02#83]
**Issue:** the styles are inconsistent between the `ListItem` component (the component on `Home.js`) and the `CompleteItem` and `Answer` components (the ones you see on `GiveAnswer.js`).

**Fix:** update the styles on `CompleteItem` and `Answer` to match those of `ListItem`.

**Comment by hanenWahabi** [comment]
I made some changes to these components, but maybe after merging you can verify

**Comment by etorres07** [comment]
Much better!

Thank you @hanenWahabi :)
