### ISSUE TITLE
'resize-mode' is an invalid property

### ISSUE THREAD

**Issue by etorres07** [chingu-voyages/v8-chimeras-team-02#84]
**Issue:** I have identified, at least on `LogIn.js`, an invalid CSS statement: `resize-mode: contain`.

**Fix:** identify other possible locations of the same statement and eliminate or replace with intented valid CSS property.

**Comment by cMikolai** [comment]
I'll fix it

**Comment by etorres07** [comment]
I'm reopening because the PR is still pending. I believe it is PR #91.
