### ISSUE TITLE
When user clicks on "My Questions" it displays 0 results while loading.

### ISSUE THREAD

**Issue by cMikolai** [chingu-voyages/v8-chimeras-team-02#89]
I suggest it would be better to display a loading message/spinning icon while loading and then render either 0 results or the questions.

**Comment by etorres07** [comment]
When I click "My Questions" I don't see the behavior you mention, @cMikolai. Would you mind sharing a .gif or screenshot of your experience?

**Comment by cMikolai** [comment]
Yeah looks fixed already, I'll close the issue.

**Comment by cMikolai** [comment]
Looks fixed already
