### ISSUE TITLE
GiveAnswer – Answer design

### ISSUE THREAD

**Issue by cMikolai** [chingu-voyages/v8-chimeras-team-02#90]
I think the solved-icon should be somewhere on the home page maybe? Or on the question element generally?

And the element order of username, avatar, etc could be in a nicer, more clear order. Keep in mind that answers will be longer than a few letters.

**Comment by etorres07** [comment]
@cMikolai When you say the solved icon what exactly are you referring to? The green checkmark?

Do you have any suggestions for the order of the elements?

**Comment by cMikolai** [comment]
Yea, I think the green checkmark would make a lot more sense on the question, not the answer. And then showing it on the home page as well so you know which questions are answered already and which ones aren't.

For the order of elements.. if you add a lot of text to answer, it starts to look a bit off with the avatar on the site, that's what I mean. Maybe we should put the avatar on top or bottom similar to the ListItems on the home page.

<img width="914" alt="Bildschirmfoto 2019-05-02 um 18 30 45" src="https://user-images.githubusercontent.com/29103440/57090979-6d27c680-6d08-11e9-947a-caeaad601fd3.png">

**Comment by hanenWahabi** [comment]
I will replace the like icon with the check marque in the home page, but for the give answer page I think we don't need it because the user will know that the question has a correct answer from the home page
