### ISSUE TITLE
'Undefined is not a function' question error

### ISSUE THREAD

**Issue by etorres07** [chingu-voyages/v8-chimeras-team-02#93]
~~**Issue:** when user clicks the question "Undefined is not a function", there is a `TypeError: Cannot read property '_id' of null.`~~

~~**Fix:** I have the gut feeling that this is a hard coded question or hard coded user. Perhaps we just need to remove the question from the db?~~

~~_Edit:_ if the user is logged in, he/she is able to see the "Undefined is not a function" question; in other words, the user doesn't get the error.~~

## EDIT 2:

**Issues:**

As a logged out user, I am getting the following errors when clicking on specific questions:
1. `TypeError: Cannot read property 'title' of undefined` (when clicking question "What is console.log?")
2. `TypeError: Cannot read property '_id' of null` (when clicking questions "New question" and "Is PHP worth learning?")

If I am logged in, I no longer get error 2 mentioned above, only error 1. 

**Steps to recreate:**
1. As a logged out user, click on the following questions: "What is console.log?"; "New question"; and "Is PHP worth learning?"
2. Repeate the previous step **while logged in**.

**Additional comments:**
By looking at the GraphQL playground, I noticed that these questions are the only ones with answers. Perhaps there is some kind of authorization bug?

**Comment by ghost** [comment]
Fixed :D

**Comment by etorres07** [comment]
I have reopened the issue. Please see **Edit 2** of the original issue.

I believe this is a strictly backend bug. In any case, please, let me know if there is anyway I can help with this.

**Comment by ghost** [comment]
The problem is that those questions have answers without a user.
Quick fix: make user not required (this would solve this issue, but makes that answer not delete-able)
Proper fix: find out why some answers don't have a user associated with them, and fix that

**Comment by ghost** [comment]
Part two of this problem: if there are answers the GiveAnswer.js page expects a current user, even when the user isn't logged in
